### ISSUE TITLE
Support for CentOS 7?

### ISSUE THREAD

**Issue by crashzk** [MaximeMichaud/Azuriom-install#16]
Would support for CentOS 7 be possible?

**Comment by MaximeMichaud** [comment]
Hi, support for CentOS 7 is not planned. 
Why would you need to use CentOS over Debian/Ubuntu ? If CentOS is supported , this would be CentOS Stream 9.

**Comment by crashzk** [comment]
My understanding is that currently my VPS uses CentOS 7 for CWP hosting.  In any case, I'll be trying to install without the script, thanks.

**Comment by MaximeMichaud** [comment]
The script is probably not compatible with this panel.
You should try without the script, the script has been made for clean VPS.
